# Generated by Django 2.1 on 2019-12-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_books', to='webapp.Book', verbose_name='Книга')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='webapp.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('write down', 'На списание'), ('purchase', 'На закупку')], default='purchase', max_length=20)),
                ('status', models.CharField(choices=[('new', 'На рассмотрении'), ('approved', 'Одобрена'), ('reject', 'Отклонена')], default='new', max_length=20)),
                ('request_book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_book', to='webapp.Book')),
            ],
        ),
    ]
