# Generated by Django 2.1 on 2019-12-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191210_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Принят', 'Принят'), ('Отменён', 'Отменён')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
