# Generated by Django 2.1 on 2019-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191210_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Электронная версия', 'e-version'), ('Бумажная книга', 'print version')], default='Бумажная книга', max_length=50, verbose_name='Статус'),
        ),
    ]
