# Generated by Django 2.1 on 2019-12-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191210_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orders', through='webapp.OrderBook', to='webapp.Book', verbose_name='Книги'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_books', to='webapp.Order', verbose_name='Заказ'),
        ),
    ]
