# Generated by Django 2.1 on 2019-12-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_orderbook_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='amount',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='webapp.Book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='webapp.Order', verbose_name='Заказ'),
        ),
    ]
