# Generated by Django 2.1 on 2019-12-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191214_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_books', to='webapp.Book', verbose_name='Книга')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='order',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_book',
        ),
        migrations.AddField(
            model_name='order',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='webapp.Publisher'),
        ),
        migrations.DeleteModel(
            name='OrderBook',
        ),
        migrations.AddField(
            model_name='requestbook',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_books', to='webapp.Request', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(related_name='order_books', to='webapp.RequestBook', verbose_name='Книга'),
        ),
    ]
